application:
  input:
    - name: 'AWAvenue-Ads-Rule-Replenish'
      path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Replenish.txt'
      type: dns

    - name: '晴雅广告拦截规则'
      path: 'https://raw.githubusercontent.com/790953214/qy-Ads-Rule/main/black.txt'
      type: dns

    - name: 'QuarkList'
      path: 'https://raw.githubusercontent.com/bamf2077/quarklist/master/dist/quarklist.txt'
      type: dns

    - name: 'SMAdHosts'
      path: 'https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/master/SMAdHosts'
      type: hosts

    - name: '10007'
      path: 'https://raw.githubusercontent.com/lingeringsound/10007/main/all'
      type: dns

    - name: '酷安规则'
      path: 'https://raw.githubusercontent.com/HAI010415/HAIADLJ/refs/heads/main/mydnsad-251128.txt'
      type: dns

    - name: 'AdGuard DNS filter'
      path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt'
      type: dns

    - name: 'AdGuard基础规则'
      path: 'https://filters.adtidy.org/android/filters/2_optimized.txt'
      type: dns

    - name: 'AdGuard移动规则'
      path: 'https://filters.adtidy.org/android/filters/11_optimized.txt'
      type: dns

    - name: 'AWAvenue-Ads-Rule'
      path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      type: dns

    - name: 'jiekouAD'
      path: 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt'
      type: dns

    - name: '乘风广告过滤规则'
      path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt'
      type: dns

    - name: 'AdGuard中文过滤规则'
      path: 'https://filters.adtidy.org/android/filters/224_optimized.txt'
      type: dns

    - name: '乘风视频过滤规则'
      path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
      type: dns

    - name: '乘风小众视频过滤规则'
      path: 'https://gcore.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule/minority-mv.txt'
      type: dns

    - name: 'HaGeZi Light DNS Blocklist'
      path: 'https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/light.txt'
      type: dns

    - name: 'AdRules DNS List'
      path: 'https://gitlab.com/cats-team/adrules/-/raw/main/dns.txt'
      type: dns

    - name: 'halflife-list-phone'
      path: 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt'
      type: dns

    - name: 'DD-AD 主规则'
      path: 'https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/dns.txt'
      type: dns

    - name: 'DD-AD 私有规则'
      path: 'https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/DD-AD.txt'
      type: dns

    - name: 'Local User Rules'
      path: 'rule/local-user.txt'
      type: dns

  output:
    file_header: |
      Custom AdBlock ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Description: ${desc}
      Generated By: ad-filters-subscriber

    files:
      - name: 'adguard-dns-merged.txt'
        type: dns
        desc: 'Merged DNS rules for AdGuard Home'
        filter:
          - basic
          - wildcard
          - unknown
        rule:
          - 'AWAvenue-Ads-Rule-Replenish'
          - '晴雅广告拦截规则'
          - 'QuarkList'
          - 'SMAdHosts'
          - '10007'
          - '酷安规则'
          - 'AdGuard DNS filter'
          - 'AdGuard基础规则'
          - 'AdGuard移动规则'
          - 'AWAvenue-Ads-Rule'
          - 'jiekouAD'
          - '乘风广告过滤规则'
          - 'AdGuard中文过滤规则'
          - '乘风视频过滤规则'
          - '乘风小众视频过滤规则'
          - 'HaGeZi Light DNS Blocklist'
          - 'AdRules DNS List'
          - 'halflife-list-phone'
          - 'DD-AD 主规则'
          - 'DD-AD 私有规则'
          - 'Local User Rules'
