application:

  input:

    - name: 'AdGuard DNS filter'
      path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt'

    - name: 'AdGuard基础规则'
      path: 'https://filters.adtidy.org/android/filters/2_optimized.txt'

    - name: 'AdGuard中文过滤规则'
      path: 'https://filters.adtidy.org/android/filters/224_optimized.txt'

    - name: 'HaGeZi Light DNS Blocklist'
      path: 'https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/light.txt'

    - name: 'AdRules DNS List'
      path: 'https://gitlab.com/cats-team/adrules/-/raw/main/dns.txt'

    - name: 'halflife-list-phone'
      path: 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt'
      
    - name: 'GoodbyeAds'
      path: 'https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt'

    - name: '1Hosts-Lite'
      path: 'https://badmojr.github.io/1Hosts/Lite/adblock.txt'

    - name: 'anti-ad'
      path: 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt'

    - name: 'OISD'
      path: 'https://small.oisd.nl'

    - name: 'StevenBlack'
      path: 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
      type: hosts

  output:
    file_header: |
      Custom AdBlock ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Generated By: ad-filters-subscriber

    files:
      - name: adguard-dns-merged.txt
        type: dns
        desc: 'Merged DNS blocklist'
        rule:
          - AdGuard DNS filter
          - AdGuard基础规则
          - AdGuard中文过滤规则
          - HaGeZi Light DNS Blocklist
          - AdRules DNS List
          - halflife-list-phone
          - 1Hosts-Lite
          - anti-ad
          - OISD  
          - StevenBlack
          - GoodbyeAds

